const TEST_MONGODB_CNX_STR = process.env.TEST_MONGODB_CNX_STR
const PROD_MONGODB_CNX_STR = process.env.PROD_MONGODB_CNX_STR

export let MONGODB_CNX_STR
if (process.env.NODE_ENV === 'PROD') {
  MONGODB_CNX_STR = PROD_MONGODB_CNX_STR
} else {
  MONGODB_CNX_STR = TEST_MONGODB_CNX_STR
}